- platform: ffmpeg
  input: !secret bcam_input_string
  name: BCam

- platform: ffmpeg
  input: !secret yicam_input_string
  name: Basement Camera

- platform: environment_canada

- platform: mjpeg
  name: OctoPrint
  still_image_url: http://octopi.chrisbox.ca/webcam/?action=snapshot
  mjpeg_url: http://octopi.chrisbox.ca/webcam/?action=stream
