project_id: home-assist-bd1a0
api_key: !secret google_assistant_api
expose_by_default: true
exposed_domains:
    - light
entity_config:
  media_player.sony_bravia_tv:
    name: "Sony TV"
    expose: true
  media_player.marantzlivingroom:
    name: "Stereo"
    aliases:
      - "Living Room Stereo"
    expose: true
  lock.front_door:
    name: "dinosaur"
    expose: true
  scene.babytime:
    name: "Baby Time Living Room Lights"
    expose: true
  scene.babytimebedroom:
    name: "Baby Time Bedroom"
    expose: true
