#-------------
#Group Entities
#-------------

people:
  name: Households
  entities:
    - device_tracker.google_maps_112273907813731668515
    - device_tracker.google_maps_114377841267658724874
    - device_tracker.64a2f9bd08ee
    - device_tracker.404e367fc94e

booleans:
  name: Booleans
  entities:
    - input_boolean.chrishome
    - input_boolean.kathrynhome

all_lights:
  name: All lights in the House
  entities:
    - group.living_room_lights
    - group.kitchen_lights
    - group.family_room_lights
    - group.basement_bathroom_lights
    - group.basement_lights
    - group.baby_bedroom_lights
    - group.parent_bedroom_lights
    - group.finnicks_bedroom_lights

reset_lights:
  name: Resets this group to white
  entities:
    - group.living_room_lights
    - group.family_room_lights
    - group.kitchen_lights
    - group.basement_lights
#-------------
#Group Entities
#-------------
living_room_lights:
  name: Living Room Lights
  entities:
    - light.speaker_lamp
    - light.couch_lamp

family_room_lights:
  name: Family Room Lights
  entities:
    - light.reading_lamp
    - light.rgblight1

basement_bathroom_lights:
  name: Basement Bathroom Lights
  entities:
    - light.0x7ce5240000046b99_light
    - light.0x7ce524000002c0f3_light

kitchen_lights:
  name: Kitchen Lights
  entities:
    - light.kitchen_light_strip

basement_lights:
  name: Basement Lights
  entities:
    - light.basement_stairs_spot_lights
    - switch.basement_lights

parent_bedroom_lights:
  name: Parent BedRoom Lights
  entities:
    - light.kathryns_lamp
    - light.chris_lamp
    - light.parents_bedroom_main_lights

finnicks_bedroom_lights:
  name: Finnicks BedRoom Lights
  entities:
    - light.finnicks_bedroom_ceiling
    - light.finnicks_light

baby_bedroom_lights:
  name: Baby BedRoom Lights
  entities:
    - light.baby_light
    - light.spare_bedroom_main_lights

living_room_television:
  name: Television
  entities:
    - media_player.bravia_4k_2015
    - media_player.living_room_tv
    - media_player.sony_bravia_tv
    - sensor.boxtifers_plex

living_room_audio:
  name: Audio Components
  entities:
    - media_player.marantzlivingroom
    - media_player.living_room_audio

living_room_devices:
   name: Devices and Stats
   entities:
    - device_tracker.f0def17e5ab1
    - device_tracker.0006781e0688
    - device_tracker.001788191d23
    - device_tracker.086a0ad82301
    - device_tracker.10bf4889dffe
    - device_tracker.546009e5e57e
    - device_tracker.788a207f314a
    - device_tracker.a47733cf1965
    - device_tracker.ac9b0ad785c8
    - device_tracker.b827eb64756e
    - device_tracker.bc60a7c19e5c
    - device_tracker.f0def17e5ab1
    - device_tracker.fc7516871fde
    - sensor.nzbget_download_paused
    - sensor.nzbget_queue_size
    - sensor.nzbget_speed

w520_sensors:
  name: "Lenovo W520 Server"
  entities:
    - sensor.last_boot
    - sensor.processor_use
    - sensor.memory_use_percent
    - sensor.swap_use_percent

nzbget:
  name: "NZBGet Stats"
  entities:
    - sensor.nzbget_download_paused
    - sensor.nzbget_queue_size
    - sensor.nzbget_speed

phones:
  name: Phones
  entities:
    - device_tracker.404e367fc94e
    - device_tracker.4c664176e87f
    - device_tracker.502e5cef4a60
    - device_tracker.c0eefb32a864
    - device_tracker.c0eefbd04847

gmaps:
  name: "Google Maps"
  entities:
    - camera.chris
    - camera.kathryn
