#- platform: denonavr
#  host: !secret denonip
#  name: MarantzLivingRoom
#  timeout: 3
#  zones:
#    - zone: Zone2
#      name: LivingRoom

#BraviaTV
- platform: braviatv
  host: !secret braviaip

- platform: androidtv
  name: Sony TV
  host: !secret braviaip
  device_class: androidtv
