- name: "BedroomDay"
  entities:
     light.kathryn_lamp:
       state: true
     light.chris_lamp:
       state: true
       color_temp: 154
       brightness_pct: 100
       transition: 1
     light.horselight:
       state: true
       color_temp: 154
       brightness_pct: 100

- name: "BabyTimeBedroom"
  entities:
     light.kathryn_lamp:
       state: false
     light.chris_lamp:
       state: false
     light.horselight:
       state: false

- name: "BookTime"
  entities:
     light.kathryn_lamp:
       state: true
       brightness_pct: 35
     light.chris_lamp:
       state: false
     light.horselight:
       state: false

- name: "NormalLights"
  entities:
     group.reset_lights:
      state: true
      color_temp: 154
      transition: 1
      brightness_pct: 100

- name: "LightsOnTime"
  entities:
    group.living_room_lights:
      state: true
      color_temp: 154
      transition: 3
      brightness_pct: 100
    group.family_room_lights:
      state: true
      color_temp: 154
      transition: 3
      brightness_pct: 100

- name: "LightsOnTimeSlow"
  entities:
    group.living_room_lights:
      state: true
      color_temp: 154
      transition: 3600
      brightness_pct: 100
    group.family_room_lights:
      state: true
      color_temp: 154
      transition: 3600
      brightness_pct: 100

- name: "LightsPlex"
  entities:
    group.living_room_lights:
      state: true
      transition: 10
      brightness_pct: 10
      xy_color: [0.672,0.324]
    group.kitchen_lights:
      state: false
      transition: 10

- name: "LightsPlexPause"
  entities:
    group.kitchen_lights:
      state: true
      brightness_pct: 75
      color_temp: 154
      transition: 2
    light.speaker_lamp:
      state: true
      brightness_pct: 75
      color_temp: 154
      transition: 2
    light.couch_lamp:
      state: true
      brightness_pct: 75
      color_temp: 154
      transition: 2

- name: "LightsOnGettingDark"
  entities:
    light.rbglight1:
      state: true
      brightness_pct: 100
      color_temp: 500
    light.reading_lamp:
      state: true
      brightness_pct: 100
      color_temp: 500
      transition: 60
    light.speaker_lamp:
      state: true
      brightness_pct: 100
      color_temp: 500
      transition: 60
    light.couch_lamp:
      state: true
      brightness_pct: 100
      color_temp: 500
      transition: 60

- name: "LightsOnGettingDarkSlow"
  entities:
    light.rgblight1:
      state: true
      brightness_pct: 100
      color_temp: 500
    light.reading_lamp:
      state: true
      brightness_pct: 100
      color_temp: 500
      transition: 3600
    light.speaker_lamp:
      state: true
      brightness_pct: 100
      color_temp: 500
      transition: 3600
    light.couch_lamp:
      state: true
      brightness_pct: 100
      color_temp: 500
      transition: 3600

- name: "SinkLight"
  entities:
    light.sink_light:
      state: true
      brightness_pct: 100
      color_temp: 154
      transition: 3

- name: "SinkLightDark"
  entities:
    light.sink_light:
      state: true
      brightness_pct: 100
      color_temp: 500
      transition: 3

- name: "StoveLight"
  entities:
    light.stove_light:
      state: true
      brightness_pct: 100
      color_temp: 154
      transition: 3
    light.sink_light:
      state: true
      brightness_pct: 100
      color_temp: 154
      transition: 3

- name: "StoveLightDark"
  entities:
    light.stove_light:
      state: true
      brightness_pct: 100
      color_temp: 500
      transition: 3
    light.sink_light:
      state: true
      brightness_pct: 100
      color_temp: 500
      transition: 3
