#ENVIRONMENTAL CANADA IMPORT
- platform: environment_canada
  
#SYSTEMMONITOR FOR SYSTEM MONTIORING
- platform: systemmonitor
  resources:
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: swap_use_percent
    - type: processor_use
    - type: last_boot

#WASHER SENSOR
- platform: mqtt
  name: "Washer State"
  state_topic: "hass/state/washer"
  icon: mdi:washing-machine

- platform: mqtt
  name: "Dryer State"
  state_topic: "dryer/pi"
  icon: mdi:tumble-dryer
