title: Box's Awesome Home
views:
    # View tab title.
  - title: Home
    icon: mdi:home-outline
    panel: true
    # Makes the first card fill the view
    cards:
        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.

