- platform: mqtt
  name: Kathryn Lamp
  command_topic: "cmnd/rgblight2/POWER"
  state_topic: "stat/rgblight2/RESULT"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tele/rgblight2/LWT"
  brightness_command_topic: "cmnd/rgblight2/Dimmer"
  brightness_state_topic: "stat/rgblight2/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  color_temp_command_topic: "cmnd/rgblight2/CT"
  color_temp_state_topic: "stat/rgblight2/STATE"
  color_temp_value_template: "{{value_json.CT}}"
  rgb_command_topic: "cmnd/rgblight2/Color2"
  rgb_state_topic: "stat/rgblight2/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "cmnd/rgblight2/Scheme"
  effect_state_topic: "stat/rgblight2/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
    - 0
    - 1
    - 2
    - 3
    - 4
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false 
